### PR TITLE
Add a draft specification of chain synchronization

### LINKED ISSUE #45: Implement the chain synchronization mini-protocol
We shall implement the chain synchronization mini-protocol as specified in Section 3.7 of [The Shelley Networking Protocol](https://input-output-hk.github.io/ouroboros-network/pdfs/network-spec/network-spec.pdf).

### PR DESCRIPTION
**Pull request by javierdiaz72**
This will ultimately resolve #45.

### CODE REVIEW

**Review by jeltsch — CHANGES_REQUESTED** [review]
I have looked through the whole specification of the chain synchronization protocol. I haven’t looked at all the details, but I came up with some initial questions and ideas, which are as follows:

  * Why are so many types specified as countable? Shouldn’t embeddable be enough?

  * I find the numbering somewhat confusing and problematic. For example, the genesis block has slot number −1 and block number 0, which not only constitutes sort of a mismatch but also necessitates allowing for negative slot numbers.

  * Why not just exclude handling of the genesis block entirely from this specification? A common genesis block should be already shared by the parties anyhow and thus never be transferred.

  * Why do regular blocks only optionally contain hashes?

  * The specification defines points to be just slot numbers. Shouldn’t they rather be hashes, something that identifies blocks (not slots) and identifies them also across conflicting chains? With slot numbers, we cannot distinguish between competing blocks that were created in the same slots. As a result, the specified approach of finding an intersection point doesn’t work. It just takes the longer one of the producer and the consumer chain as the “intersection”.

  * Why do we have to deal with slots at all? Aren’t they immaterial to the problem of chain synchronization?

  * So far, things seem too complicated to me. There are details modeled that should be immaterial to chain synchronization. At least as long as we handle chain synchronization in isolation and don’t yet know how we might integrate it with other specifications of ours in the future, we should go for a simple approach like the following one:

      - Use an unspecified type for hashes (IDs).

      - Models regular blocks simply as their IDs (without any payload) or as pairs of an ID and a payload of arbitrary but fixed type (use a type variable here).

    Actually, we could probably stay that abstract and still allow for future composition with other specifications. My idea for that would be to use type variables for things like hashes and blocks and specify that there are certain operations like getting the hash of a block (this all should probably be done using locales). Then we could later instantiate these things to something more concrete from other specifications.

  * Should tips be blocks? I thought they should be points. I agree that the semi-formal specification is vague here. Maybe we can just leave out the communication of tips, as it doesn’t seem to be crucial for the protocol.

  * Things like the list of candidate intersection points and the intersection point found are part of the internal state of the producer. This shouldn’t be necessary, as the producer can just find an intersection point and respond with a corresponding message on the fly.

    I guess the necessity to store this data in the internal state has to do with the way the producer and the consumer are implemented. The recursion happens once a state of the state machine has been entered, before any previous state transition has been handled. As a result, data from incoming messages has to be preserved for the next recursive invocation.

    Unfortunately, this leads to a large internal state of which many parts are only used occasionally. A particular problem of that is that in most, if not all, situations there are internal states that are possible according to the type but illegal in the current situation, because the contain or lack certain data.

  * I wonder whether we can improve the representation of the blockchain. The type used at the moment permits chains with non-ascending block numbers. We could represent chains as finite maps from slot numbers to blocks, for example, so that only valid chains could be represented. Of course, this all only applies as long as we deal with slot numbers at all. If we drop them, as I suggest above, we can model a blockchain just as a list of blocks.

  * The code uses process families, when actually processes should be constructed, using the typed interface. What’s worse, it seeks to combine the typed interface with families, using such types as `message channel family`, for which the process (family) constructors are simply not defined (they are necessarily declared with very general types, which is why this error isn’t caught by the type checker).

  * Why does `new_chain_switcher` mention a *channel* for producer parameters?

  * The `new_chain_switcher` process doesn’t seem to reset `must_rollback` after a rollback has been signaled.

Since we now plan to specify and verify the chain synchronization protocol on the level of state machines and consider this present specification a mere draft, not all of the above points have to be addressed in this pull request. That said, at least the issue with blocks being identified by slot numbers, which leads to an incorrect approach of finding intersection points, should be fixed.

**Comment by javierdiaz72** [comment]
>

**Comment by javierdiaz72** [comment]
Thanks a lot for your initial review, which includes very interesting points. I'll share my thoughts on each point in a separate message so that you can have more immediate feedback. :slightly_smiling_face: 

>     * Why are so many types specified as countable? Shouldn’t embeddable be enough?
In effect, `embeddable` should be enough and I think we should definitely use it for our refined specification. It's just that, for this draft specification, I found it quicker to use the `countable_datatype` proof method instead of explicitly dealing with injections from those types into `V`.

**Comment by javierdiaz72** [comment]
Reopening the pull request, since I accidentally dropped it.

**Comment by jeltsch** [comment]
> In effect, `embeddable` should be enough and I think we should definitely use it for our refined specification. It's just that, for this draft specification, I found it quicker to use the `countable_datatype` proof method instead of explicitly dealing with injections from those types into `V`.

Yes, I think they don’t have an analog of the `countable_datatype` proof method for `embeddable` yet. Let’s go for `embeddable` in the future. I guess for the finite state machine we don’t even need *any* class constraint, as `embeddable` is only needed when working with the Þ-calculus.

**Comment by javierdiaz72** [comment]
> I find the numbering somewhat confusing and problematic. For example, the genesis block has slot number −1 and block number 0, which not only constitutes sort of a mismatch but also necessitates allowing for negative slot numbers.

Agreed, I don't like negative slot numbers neither.

> Why not just exclude handling of the genesis block entirely from this specification? A common genesis block should be already shared by the parties anyhow and thus never be transferred.

I thought about that at the beginning. Incidentally, note that, for example, our Praos specification in Isabelle does not include genesis blocks in chains. However, this makes some parts of the code, such as finding the intersection point, a bit less homogeneous in case there is no intersection point but the genesis block. That's why I thought that, from an abstract point of view, including genesis blocks in chains was a better option. Of course, for simplicity we could (and perhaps should) just exclude handling of genesis blocks entirely.

**Comment by jeltsch** [comment]
> However, this makes some parts of the code, such as finding the intersection point, a bit less homogeneous in case there is no intersection point but the genesis block.

We could use the `option` type here, representing the genesis block by `None` and any regular block `b` by `Some b`.

**Comment by javierdiaz72** [comment]
> Why do regular blocks only optionally contain hashes?

The hash in a regular block is a "pointer" to the previous block. Originally, the optionality was included to handle the case of the first block, which can be regarded as not having a previous block. However, we could (and maybe should, as per the CDDL definition in the specification document) assume that the previous block of the first block is the genesis block and thus use its hash (which, I guess, should exist).

**Comment by javierdiaz72** [comment]
> The specification defines points to be just slot numbers. Shouldn’t they rather be hashes, something that identifies blocks (not slots) and identifies them also across conflicting chains? With slot numbers, we cannot distinguish between competing blocks that were created in the same slots. As a result, the specified approach of finding an intersection point doesn’t work. It just takes the longer one of the producer and the consumer chain as the “intersection”.

You're correct. Actually, the current specification includes a FIXME that says that we should add a hash, as suggested in the CDDL definition in the specification document (which I find a bit unclear with respect to the definition of points).

**Comment by javierdiaz72** [comment]
> [..] we should go for a simple approach like the following one: [...]

I agree with a simpler approach along those lines.

**Comment by javierdiaz72** [comment]
> Should tips be blocks? I thought they should be points. I agree that the semi-formal specification is vague here. Maybe we can just leave out the communication of tips, as it doesn’t seem to be crucial for the protocol.

According to the CDDL encoding specification, the definition of `tip` is `[point, uint]`, so indeed tips are not strictly blocks but a sort of pointers (I'm not sure what the `uint` component refers to, though).

I was tempted to leave out the communication of tips, however I think we should consult with Duncan first.

**Comment by javierdiaz72** [comment]
>Things like the list of candidate intersection points and the intersection point found are part of the internal state of the producer. This shouldn’t be necessary, as the producer can just find an intersection point and respond with a corresponding message on the fly.

That's true and actually I had already thought about it. But, as I understand it, that would deviate from the semi-formal specification, for example the `StIntersect` state would not be needed anymore. I'm not sure whether we should strictly stick to the semi-formal specification or we can make such improvements.

**Comment by javierdiaz72** [comment]
>I wonder whether we can improve the representation of the blockchain. [..]

Sure, I think we can improve it as you say.

**Comment by javierdiaz72** [comment]
>Why does new_chain_switcher mention a channel for producer parameters?

That channel `I` is used for the recursive invocations and `pp` contains the parameters of the current invocation.

**Comment by jeltsch** [comment]
> > Things like the list of candidate intersection points and the intersection point found are part of the internal state of the producer. This shouldn’t be necessary, as the producer can just find an intersection point and respond with a corresponding message on the fly.
> 
> That's true and actually I had already thought about it. But, as I understand it, that would deviate from the semi-formal specification, for example the `StIntersect` state would not be needed anymore. I'm not sure whether we should strictly stick to the semi-formal specification or we can make such improvements.

Well, the responding should be separate, I agree. However, the computation of the intersection point might be done upon receipt of the message. I guess the intersection point is what the read pointer has to become; so we wouldn’t need extra state for remembering the intersection point to be included in the response but could just use the read pointer.

**Comment by javierdiaz72** [comment]
> > > Things like the list of candidate intersection points and the intersection point found are part of the internal state of the producer. This shouldn’t be necessary, as the producer can just find an intersection point and respond with a corresponding message on the fly.
> > 
> > 
> > That's true and actually I had already thought about it. But, as I understand it, that would deviate from the semi-formal specification, for example the `StIntersect` state would not be needed anymore. I'm not sure whether we should strictly stick to the semi-formal specification or we can make such improvements.
> 
> Well, the responding should be separate, I agree. However, the computation of the intersection point might be done upon receipt of the message. I guess the intersection point is what the read pointer has to become; so we wouldn’t need extra state for remembering the intersection point to be included in the response but could just use the read pointer.

Yes, I guess you're right, so we could implement that improvement.

**Comment by jeltsch** [comment]
> So using processes and channels instead of process families and channel families would be fine? I thought that the use of the typed layer implied the use of families. Could you please elaborate a bit on that?

The use of the typed layer implies *not* using families. :slightly_smiling_face:

Process families are the HOAS equivalent of potentially open processes (processes that may contain free variables), and what we call processes are the HOAS equivalent of closed processes (processes that may not contain free variables). We need process families for the operational semantics and bisimilarity reasoning based on it. However, when specifying a protocol or implementing it, we don’t need to deal with environments, and therefore processes are enough. They are actually simpler to use; in particular, we don’t need to use `□` anymore. Note that a process is just a constant process family; so, when reasoning about specifications or implementations, we still have process families that we can work with.

**Comment by javierdiaz72** [comment]
> > So using processes and channels instead of process families and channel families would be fine? I thought that the use of the typed layer implied the use of families. Could you please elaborate a bit on that?
> 
> The use of the typed layer implies _not_ using families. slightly_smiling_face
> 
> Process families are the HOAS equivalent of potentially open processes (processes that may contain free variables), and what we call processes are the HOAS equivalent of closed processes (processes that may not contain free variables). We need process families for the operational semantics and bisimilarity reasoning based on it. However, when specifying a protocol or implementing it, we don’t need to deal with environments, and therefore processes are enough. They are actually simpler to use; in particular, we don’t need to use `□` anymore. Note that a process is just a constant process family; so, when reasoning about specifications or implementations, we still have process families that we can work with.

I understand now, thanks a lot for your explanation. So the typed layer is cooler than I thought. :slightly_smiling_face:

**Comment by jeltsch** [comment]
To elaborate a bit more on that: We use environments to maintain channels that were created via `ν`. We have to deal with these channels explicitly only when considering process (families) that at least originally appeared under a `ν`. There are two situations where this happens: (1) when we got a process family from a scope opening transition and (2) when performing a transition under a `ν`. When specifying or implementing things, our processes are closed and so variables introduced by `ν` are just bound (and stay this way).

**Comment by jeltsch** [comment]
> So the typed layer is cooler than I thought. slightly_smiling_face

I’m extremely happy to hear that. :heart_eyes:

**Comment by jeltsch** [comment]
To elaborate even more on that: If we wouldn’t use families *in our bisimilarity statements*, we would get into trouble later when trying to use these lemmas in proofs of other lemmas in places where we have to deal with process families that arose from scope opening.

**Comment by jeltsch** [comment]
> The use of the typed layer implies _not_ using families. slightly_smiling_face

Look at the types of the three instantiations of the process notation again: the plain and the typed one use `process`; only the family one uses `process family`.

**Comment by jeltsch** [comment]
> > Well, the responding should be separate, I agree. However, the computation of the intersection point might be done upon receipt of the message. I guess the intersection point is what the read pointer has to become; so we wouldn’t need extra state for remembering the intersection point to be included in the response but could just use the read pointer.
> 
> Yes, I guess you're right, so we could implement that improvement.

Yes, but maybe not as part of this specification, since we don’t want to stick to a direct Þ-calculus specification but instead want to go via state machines.

I expect us to ultimately drop the current specification. This seems a bit sad perhaps, but I think it had its use by making us try to understand the chain synchronization protocol better and getting a better understanding of how we should specify and prove things (we learned, for example, that going directly to the Þ-calculus is perhaps not a good idea :slightly_smiling_face:).

**Comment by jeltsch** [comment]
I think we discussed all my questions and remarks. I propose that you fix the bug that is definitely in the current specification and which arises from using slot numbers instead of hashes for finding intersection points. I think the best thing is to remove slot numbers from the specification entirely and fully rely on hashes for identifying blocks. You may also want to drop the handling of the genesis blocks, as this just unnecessarily complicates the specification.

**Comment by javierdiaz72** [comment]
> I think we discussed all my questions and remarks. I propose that you fix the bug that is definitely in the current specification and which arises from using slot numbers instead of hashes for finding intersection points. I think the best thing is to remove slot numbers from the specification entirely and fully rely on hashes for identifying blocks. You may also want to drop the handling of the genesis blocks, as this just unnecessarily complicates the specification.

Fixed in 06e163ae5449cf64341293b9bdda194612eef129, please check.

**Comment by jeltsch** [comment]
> > I think we discussed all my questions and remarks. I propose that you fix the bug that is definitely in the current specification and which arises from using slot numbers instead of hashes for finding intersection points. I think the best thing is to remove slot numbers from the specification entirely and fully rely on hashes for identifying blocks. You may also want to drop the handling of the genesis blocks, as this just unnecessarily complicates the specification.
> 
> Fixed in [06e163a](https://github.com/input-output-hk/ouroboros-high-assurance/commit/06e163ae5449cf64341293b9bdda194612eef129), please check.

As I haven’t looked at some parts of this specification, I also haven’t checked these recent changes in depth, but what I saw and understood looked reasonable. :slightly_smiling_face:

**Review by jeltsch — APPROVED** [review]

**Pull request merged**
