### PR TITLE
Replace the mini-protocol framework by a program-based one

### LINKED ISSUE #57: Replace the mini-protocol framework by a program-based one
The current mini-protocol framework uses a notion of state machine that also captures the decision-making of the client and the server. It achieves that in particular by explicitly modeling internal data as a kind of additional state. Unfortunately, this approach often doesn’t work well when information received via an incoming message has to be used in a response. Such information has to be stored as part of the internal state, since the response will happen only in a future step. This results in complex internal data and potential inconsistencies of internal data in the form of absence or presence of information where in the respective state such information should be present or absent respectively.

As a solution, we shall replace the current framework with a new one that is closer to the Haskell and Agda frameworks for mini-protocols. In particular, this new framework shall arrange for clients and servers being implemented as effectful computations whose conformance to state machines has to be proved.

### PR DESCRIPTION
**Pull request by jeltsch**
This resolves #57.

### CODE REVIEW

**Comment by jeltsch** [comment]
I give this pull request draft status for the time being, since it has turned out that my preliminary implementation of the ping-pong protocol based on this framework doesn’t work with the version above.

**Comment by jeltsch** [comment]
@javierdiaz72, do you think it would be better to disband the *Protocols* section and define the individual locales in the subsections to which they are related: `protocol_possibilities` in *Possibilities*, `protocol_state_machines` in *State Machines*, and `protocol_programs` in *Programs*?

**Comment by javierdiaz72** [comment]
> @javierdiaz72, do you think it would be better to disband the _Protocols_ section and define the individual locales in the subsections to which they are related: `protocol_possibilities` in _Possibilities_, `protocol_state_machines` in _State Machines_, and `protocol_programs` in _Programs_?

Yes, I think it would be clearer that way.

**Comment by jeltsch** [comment]
@javierdiaz72, I don’t plan to add more commits for now; so you are encouraged to write a review for the present version of this new mini-protocol framework. Please take care to take all commits into account. Thank you.

**Review by javierdiaz72 — APPROVED** [review]
Looks very nice to me.

**Pull request merged**
